# Site settings
title: IceGem Beauty
email: hello@icegembeauty.com
formspree_token: xbpqjzax # Either form token or email address
url: https://www.icegembeauty.com
domain: www.icegembeauty.com
description: "South Manchester Beauty Therapy."
ga: UA-141214565-1
lightwidget: 0e9d10cfde0b5ab2b25feb33b715b200
iguser: icegembeauty
mapsurl: https://www.google.com/maps/place/IceGem+Beauty/@53.417517,-2.3224037,17z/data=!3m1!4b1!4m5!3m4!1s0x487bad657a0a5e0d:0xc507638a525ff08b!8m2!3d53.417517!4d-2.320215
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-bg: '#F9F9F7'
  panel-bg: '#F9F9F7'
  links: '#E69500'
  text: '#333333'

# Footer settings
footer: IceGem Beauty

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/icegembeauty/

# Build settings
markdown: kramdown
permalink: pretty
